name: CS

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'release/**'
      - 'fix/**'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Lint with tox
        run: tox -e lint
